poly1305: rename fuzz output files
We can't `cargo publish` because the fuzz filenames contain colons:

    error: cannot package a filename with a special character `:`: src/fuzz/id:000000,sig:06,src:000014,op:flip4,pos:11

The full list of bad characters can be found here:

https://github.com/rust-lang/cargo/commit/eecb9009955437b8a4e89694d58a0e9faee8a892#diff-e23c793746a7be78139a4e37509a74acR248

    let bad_chars = ['/', '\\', '<', '>', ':', '"', '|', '?', '*'];

This commit changes the `:` in the filenames to `=` which should
hopefully make the crate publishable again and also preserve a delimiter
in the filenames.